version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo "Pre build stage..."
      - echo "Clone the git yaml..."
      - echo "https://${GIT_ID}:${GIT_PW}@${GIT_CD_URL}" > ~/.git-credentials
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION} --registry-ids ${ACCOUNT_ID})
  build:
    commands:
      - echo "Build stage..."
      - echo Building the Docker image... `date`
      - docker build -t ${ECR_REPO}:${CODEBUILD_BUILD_NUMBER} .
      - docker tag ${ECR_REPO}:${CODEBUILD_BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_BUILD_NUMBER}
      - docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_BUILD_NUMBER}
  post_build:
    commands:
      - echo "Post build stage..."
      - git config --global credential.helper store 
      - git config --global user.name "CodeBuild ${CODEBUILD_BUILD_NUMBER}"
      - git config --global user.email syha@megazone.com
      - git clone ${GIT_CD_URL}
      - cd ${CD_REPO_NAME}
      - $(sed -i "/        image:/ c\        image\:\ ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_BUILD_NUMBER}" server.yaml)
      - cat server.yaml
      - git add .
      - git commit -m "change container iamge ${CODEBUILD_BUILD_NUMBER}"
      - git push ${GIT_CD_URL}
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
# artifacts:
#   files:
#     - src-0.0.1-SNAPSHOT.jar
#     - appspec.yml
#     - script/*
#   discard-paths: yes