version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo "Pre build stage"
      - echo "Sync git yaml"
      - echo "https://${GIT_ID}:${GIT_PW}@${GIT_URL}" > ~/.git-credentials
      - git config credential.helper 'store'
      - git clone ${GIT_URL}
      - ls -al 
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION} --registry-ids ${ACCOUNT_ID})
  build:
    commands:
      - echo "Build stage"
      - echo Building the Docker image... `date`
      - docker build -t ${ECR_REPO}:${CODEBUILD_BUILD_NUMBER} .
      - docker tag ${ECR_REPO}:${CODEBUILD_BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_BUILD_NUMBER}
      - docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_BUILD_NUMBER}
  post_build:
    commands:
      - echo "Post build stage"
      - cd ${CD_REPO_NAME}
      - sed -i "/        image:/ c\        image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_BUILD_NUMBER}" server.yaml
      - git add .
      - git commit "change container iamge"
      - git push
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
# artifacts:
#   files:
#     - src-0.0.1-SNAPSHOT.jar
#     - appspec.yml
#     - script/*
#   discard-paths: yes